# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LMapp_for_VK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LMapp_for_VK
  #pod 'AnyCodable-FlightSchool', '~> 0.4.0'

end
