# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LMapp_for_VK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LMapp_for_VK
  pod 'RealmSwift'
  pod 'PromiseKit'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON'

end
